### ISSUE TITLE
Unhandled ECONNRESET error

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-test-web#38] opened 2022-08-03 13:50 UTC
I see the following often in my CI:

```
$ tsc ./src/test/browser/runTests.ts --outDir ./dist/browser/test --rootDir ./src/test/browser --target es6 --module commonjs
/Users/runner/work/1/s /Users/runner/work/1/s/dist/browser/test/index
Serving dev extensions from /Users/runner/work/1/s
Listening on http://localhost:3000/
events.js:377
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:209:20)
Emitted 'error' event on ClientRequest instance at:
    at TLSSocket.socketErrorListener (_http_client.js:475:9)
    at TLSSocket.emit (events.js:400:28)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  errno: -54,
  code: 'ECONNRESET',
  syscall: 'read'
}
```
(from https://dev.azure.com/vscode/vscode-pull-request-github/_build/results?buildId=70217&view=logs&j=bf770c6b-39e5-569e-4808-1859a08d14ab&t=dbcdb93c-9c4d-5e3b-231d-19272cc2845d).

This looks a lot like https://github.com/microsoft/vscode-test/issues/153. It would be great if a retry could be added for vscode-test-web too assuming it's the same issue.

**Comment by aeschli** [comment] 2023-04-05 08:51
Duplicate of https://github.com/microsoft/vscode-test-web/issues/43

In the meantime, this got fixed for the CLI. When using the API of the node module, make sure to have a `uncaughtException` handler in your test runner

**Closed** 2023-04-05 08:51 UTC
